name: TheVeug
main: com.jamesgames.theveug.Main
version: 1.0
api-version: 1.15
commands:
    reload_config:
        description: Reloads all data from the json
        usage: /<command>
    xp_rate:
        description: Sets global xp rate from all destroyed blocks
        usage: /<command> amount
    drop_rate:
        description: Sets global drop rate of all items dropped from blocks
        usage: /<command> amount
    toggle_debug_logs:
        description: Enable/Disable to view logs in console
        usage: /<command> true
    what_drops:
        description: Lists what drops the given material
        usage: /<command> material
    what_drops_from:
        description: Lists what drops from the given material
        usage: /<command> material
    level_up_item:
        description: Levels the currently held item up by 1
        usage: /<command>
    add_buff:
        description: Adds or levels buff to currently held item
        usage: /<command> buffName